name: "Patch Generator"
description: "Generates a patch when working directory is not clean."
branding:
  icon: "edit-3"
  color: "blue"
runs:
  using: "composite"
  steps:
    - id: diff
      run: |
        if git diff --binary > /tmp/git-patch
        then
          echo 'Clean'
          echo '::set-output name=result::clean'
        else
          echo 'Dirty'
          echo '::set-output name=result::dirty'
        fi
      shell: bash
    - uses: actions/upload-artifact@v2
      if: steps.diff.outputs.result == 'dirty'
      with:
        name: git-patch
        path: /tmp/git-patch
    - run: |
        (
          echo 'Oops!'
        ) | tee /tmp/git-patch-message.md
      if: steps.diff.outputs.result == 'dirty'
      shell: bash
    - uses: dtinth/markdown-report-action@af8143d37cced4c514fd67539a2e58c2f432da09
      if: steps.diff.outputs.result == 'dirty'
      with:
        name: Outdated files
        title: Some files are outdated
        body-file: /tmp/git-patch-message.md
