name: "Patch Generator"
description: "Generates a patch when working directory is not clean."
branding:
  icon: "edit-3"
  color: "blue"
runs:
  using: "composite"
  steps:
    - id: diff
      run: |
        if git diff --binary --exit-code > /tmp/fix.diff
        then
          echo 'CI worktree is clean.'
          echo '::set-output name=result::clean'
        else
          echo 'CI worktree is dirty.'
          echo '::set-output name=result::dirty'
        fi
      shell: bash
    - uses: actions/upload-artifact@v2
      if: steps.diff.outputs.result == 'dirty'
      with:
        name: git-patch
        path: /tmp/fix.diff
    - run: |
        puts
        puts "This problem can be automatically fixed."
        puts
        puts "Download the 'git-patch' artifact from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}, extract it, and run `git apply /path/to/fix.diff`"
        puts
        puts "Alternatively, run the following command:"
        puts
        puts "echo '"
        system "base64 /tmp/fix.diff"
        puts "' | base64 --decode | git apply"
        puts
        exit 1
      if: steps.diff.outputs.result == 'dirty'
      shell: ruby
