name: "Patch Generator"
description: "Generates a patch when working directory is not clean."
branding:
  icon: "edit-3"
  color: "blue"
runs:
  using: "composite"
  steps:
    - id: diff
      run: |
        if git diff --binary --exit-code > /tmp/fix.diff
        then
          echo 'CI worktree is clean.'
          echo '::set-output name=result::clean'
        else
          echo 'CI worktree is dirty. Your repository may contain outdated file.'
          echo '::set-output name=result::dirty'
        fi
      shell: bash
    - uses: actions/upload-artifact@v2
      if: steps.diff.outputs.result == 'dirty'
      with:
        name: git-patch
        path: /tmp/fix.diff
    - run: |
        echo
        echo "This problem can be automatically fixed."
        echo
        echo "Download the 'git-patch' artifact from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}, extract it, and run: 'git apply /path/to/fix.diff'"
        echo
        echo "Alternatively, run the following command:"
        echo
        echo "echo '"
        base64 /tmp/fix.diff
        echo "' | base64 --decode | git apply"
        echo
        exit 1
      if: steps.diff.outputs.result == 'dirty'
      shell: bash
