name: "Patch Generator"
description: "Generates a patch when working directory is not clean."
branding:
  icon: "edit-3"
  color: "blue"
runs:
  using: "composite"
  steps:
    - id: diff
      run: |
        if git diff --binary --exit-code > /tmp/fix.diff
        then
          echo 'CI worktree is clean.'
          echo '::set-output name=result::clean'
        else
          echo '::error::CI worktree is dirty.'
          echo '::set-output name=result::dirty'
        fi
      shell: bash
    - uses: actions/upload-artifact@v2
      if: steps.diff.outputs.result == 'dirty'
      with:
        name: git-patch
        path: /tmp/fix.diff
    - run: |
        echo
        echo $'\033[1;31m'"🚨 Your branch contains outdated files."$'\033[m'
        echo $'\033[1;37m'"💡 This problem can be automatically fixed."$'\033[m'
        echo
        echo "👉 Download and extract the 'git-patch' artifact from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} then run: 'git apply /path/to/fix.diff'"
        echo
        cat /tmp/fix.diff | gzip -9 | base64 > /tmp/fix.diff.gz.b64
        if [ "$(wc -l < /tmp/fix.diff.gz.b64)" -lt 100 ]
        then
          echo "👉 Alternatively, run the following command:"
          echo
          echo "echo '"
          cat /tmp/fix.diff.gz.b64
          echo "' | base64 --decode | gunzip | git apply"
          echo
          echo "::group::See diff contents"
          git diff --color
          echo "::endgroup::"
        fi
        exit 1
      if: steps.diff.outputs.result == 'dirty'
      shell: bash
